# Generated by Django 4.0.1 on 2022-02-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(default=4002, max_length=15, verbose_name='Digite seu telefone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='dataPub',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.CharField(max_length=200, verbose_name='Digite seu email'),
        ),
    ]
