# Generated by Django 4.0.1 on 2022-02-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_clientes_telefone_alter_clientes_datapub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='color',
            field=models.CharField(default='#FFD700', max_length=10),
        ),
    ]
