# Generated by Django 4.0.1 on 2022-02-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_alter_events_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Digite seu telefone'),
        ),
    ]
