# Generated by Django 4.0.2 on 2022-03-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_alter_clientes_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Espaço'),
        ),
    ]
